Fix regression in 'X' handling
Details

  This change fixes a regression that causes a non-fatal backtrace
  while attempting to collapse an added or deleted region:

    The fix required to ensure the 'max line length' bar is at the
    proper column position changed some font metric uses to be a
    floating point value.

    This led to a backtrace like this when pressing X:

      TypeError: arguments did not match any overloaded call:
        drawText(self, p: QPointF, s: Optional[str]): argument 1 has unexpected type 'int'
        drawText(self, rectangle: QRectF, flags: int, text: Optional[str]): argument 1 has unexpected type 'int'
        drawText(self, rectangle: QRect, flags: int, text: Optional[str]): argument 1 has unexpected type 'int'
        drawText(self, rectangle: QRectF, text: Optional[str], option: QTextOption = QTextOption()): argument 1 has unexpected type 'int'
        drawText(self, p: QPoint, s: Optional[str]): argument 1 has unexpected type 'int'
        drawText(self, x: int, y: int, width: int, height: int, flags: int, text: Optional[str]): argument 2 has unexpected type 'float'
        drawText(self, x: int, y: int, s: Optional[str]): argument 2 has unexpected type 'float'
      QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
      QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
      QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
      QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
      QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
      QPaintDevice: Cannot destroy paint device that is being painted

  Casting the argument to an integer resolves the issue.

Testing

  X works again, and no backtrace is show.